### ISSUE TITLE
Code release time？

### ISSUE THREAD

**Issue by Pythonpa** [yumingj/Text2Performer#1]
Thanks to the author. May I ask when the experience code will be released?

**Comment by johndpope** [comment]
Spoiler - S labs license. Prohibited use in commercial apps.

**Comment by spacewalkingninja** [comment]
@johndpope spoiler - I don't think anybody cares. 
When can we expect code + pretrained models + workflow pls ?

**Comment by spacewalkingninja** [comment]
@yumingj You are tasked to ASAP (got about 6 hours before I am home and programming again) release this model! You must do as task requires of you.

**Comment by yumingj** [comment]
Thanks for your interest. The code is released now!

**Comment by spacewalkingninja** [comment]
OMai THanKS WE THE OPEN SOURCE COMMUNITY love you!
