### ISSUE TITLE
Ask for pre-defined templates

### ISSUE THREAD

**Issue by xiefan233** [yumingj/Text2Performer#2]
"Upon the above labels,  we then generate texts for each video using some pre-defined templates. The texts include descriptions of the  appearances of the dressed clothes and descriptions for each sub-motions."
This is what you mentioned in your paper. What I want to ask is what is the predefined template you mentioned here? Can you give me some examples? Thank you very much!

**Comment by yumingj** [comment]
Hi,

Thanks for your interest. The captions for the appearance are [here](https://drive.google.com/file/d/1keB1zXYaeIyT9fwwLot6STGoWYUVJtjK/view?usp=sharing), and the templates for the motions are [here](https://drive.google.com/file/d/1lC7WZnont3r5NrDJeL0ddcSoyN9rIAyC/view?usp=sharing).

I am sorry for the late response.
