### ISSUE TITLE
Excuse me,I executed your code, but the performance is not as good as you showed in your paper.

### ISSUE THREAD

**Issue by zhangtao22** [yumingj/Text2Performer#5]
Anything wrong with me?

**Comment by yumingj** [comment]
Hi, [this](https://drive.google.com/file/d/1b0jK6be25IBCEpoxbM4SoCc3yTcGnV8w/view?usp=sharing) is the video generated by the code in the [jupyter notebook](https://github.com/yumingj/Text2Performer/blob/main/generate_long_video.ipynb). Hope this example could help you!
